### Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("diabetic_data.csv")
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [3]:
(df == "?").sum().sort_values(ascending=False)

weight                      98569
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
admission_type_id               0
patient_nbr                     0
encounter_id                    0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
number_diagnoses                0
max_glu_serum                   0
A1Cresult                       0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [4]:
# Replacing "?" with NaN
df.replace("?", np.nan, inplace=True)

In [6]:
df.head(15)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),NaN,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30
6,55842,84259809,Caucasian,Male,[60-70),NaN,3,1,2,4,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
7,63768,114882984,Caucasian,Male,[70-80),NaN,1,1,7,5,...,No,No,No,No,No,No,No,No,Yes,>30
8,12522,48330783,Caucasian,Female,[80-90),NaN,2,1,4,13,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
9,15738,63555939,Caucasian,Female,[90-100),NaN,3,3,4,12,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
10,28236,89869032,AfricanAmerican,Female,[40-50),NaN,1,1,7,9,...,No,Steady,No,No,No,No,No,No,Yes,>30
11,36900,77391171,AfricanAmerican,Male,[60-70),NaN,2,1,4,7,...,No,Steady,No,No,No,No,No,Ch,Yes,<30
12,40926,85504905,Caucasian,Female,[40-50),NaN,1,3,7,7,...,No,Down,No,No,No,No,No,Ch,Yes,<30
13,42570,77586282,Caucasian,Male,[80-90),NaN,1,6,7,10,...,No,Steady,No,No,No,No,No,No,Yes,NO
14,62256,49726791,AfricanAmerican,Female,[60-70),NaN,3,1,2,1,...,No,Steady,No,No,No,No,No,No,Yes,>30

In [7]:
df.isnull().sum().sort_values(ascending=False)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [8]:
# Dropping weight column since it has too many null values
df.drop(columns=["weight"], inplace=True)

In [9]:
# fixing gender column
df["gender"] = df["gender"].replace("Unknown/Invalid", "Unknown")

##### Replacing missing values

In [10]:
text_cols = [
    "race",
    "payer_code",
    "medical_specialty",
    "diag_1",
    "diag_2",
    "diag_3",
    "max_glu_serum",
    "A1Cresult"
]

df[text_cols] = df[text_cols].fillna("Unknown")

In [13]:
# verifying if nulls are there
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

##### Readmission flag

In [14]:
df["ReadmissionFlag"] = (df["readmitted"] == "<30").astype(int)

##### Readmission category

In [17]:
df["ReadmissionCategory"] = df["readmitted"].replace({
    "<30":"Within 30 days",
    ">30":"After 30 days",
    "NO":"Not readmitted"
})

##### Length of Stay Buckets

In [18]:
df["LOS_Bucket"] = pd.cut(df["time_in_hospital"], bins=[0, 3, 7, 14, 100], labels=["1-3 Days","4-7 Days","8-14 Days","15+ Days"])

##### Total Prior Visits

In [19]:
df["TotalPriorVisits"] = (df["number_outpatient"] + df["number_emergency"] + df["number_inpatient"])

##### Prior Visit Buckets

In [20]:
df["PriorVisitBucket"] = pd.cut(df["TotalPriorVisits"], bins=[-1, 0, 2, 5, 100], labels=["None","1-2 Visits","3-5 Visits","5+ Visits"])

##### Medication Load

In [21]:
df["MedicationLoad"] = pd.cut(df["num_medications"],bins=[0, 10, 20, 50, 100],
    labels=["Low","Medium","High","Very High"])

##### Check Readmission Distribution

In [22]:
df["ReadmissionCategory"].value_counts()

ReadmissionCategory
Not readmitted    54864
After 30 days     35545
Within 30 days    11357
Name: count, dtype: int64

In [23]:
df["ReadmissionFlag"].value_counts()

ReadmissionFlag
0    90409
1    11357
Name: count, dtype: int64

In [24]:
df["age"].unique()

array(['[0-10)', '[10-20)', '[20-30)', '[30-40)', '[40-50)', '[50-60)',
       '[60-70)', '[70-80)', '[80-90)', '[90-100)'], dtype=object)

In [25]:
print(df.shape)

print("Unique Patients:",
      df["patient_nbr"].nunique())

print("Unique Encounters:",
      df["encounter_id"].nunique())

(101766, 55)
Unique Patients: 71518
Unique Encounters: 101766

In [26]:
print(df["admission_type_id"].value_counts().sort_index())

print(df["discharge_disposition_id"].value_counts().sort_index())

print(df["admission_source_id"].value_counts().sort_index())

admission_type_id
1    53990
2    18480
3    18869
4       10
5     4785
6     5291
7       21
8      320
Name: count, dtype: int64
discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
11     1642
12        3
13      399
14      372
15       63
16       11
17       14
18     3691
19        8
20        2
22     1993
23      412
24       48
25      989
27        5
28      139
Name: count, dtype: int64
admission_source_id
1     29565
2      1104
3       187
4      3187
5       855
6      2264
7     57494
8        16
9       125
10        8
11        2
13        1
14        2
17     6781
20      161
22       12
25        2
Name: count, dtype: int64

##### Admission type map

In [27]:
admission_type_map = {
    1: "Emergency",
    2: "Urgent",
    3: "Elective",
    4: "Newborn",
    5: "Not Available",
    6: "Unknown",
    7: "Trauma Center",
    8: "Other"
}

df["AdmissionType"] = df["admission_type_id"].map(admission_type_map)

##### admission source map

In [28]:
admission_source_map = {
    1: "Physician Referral",
    2: "Clinic Referral",
    3: "HMO Referral",
    4: "Transfer from Hospital",
    5: "Transfer from Skilled Nursing Facility",
    6: "Transfer from Health Care Facility",
    7: "Emergency Room",
    8: "Court/Law Enforcement",
    9: "Not Available",
    10: "Transfer from Critical Access Hospital",
    11: "Normal Delivery",
    13: "Sick Baby",
    14: "Extramural Birth",
    17: "Unknown",
    20: "Transfer from Another Facility",
    22: "Born Inside Hospital",
    25: "Transfer from Ambulatory Surgery Center"
}

df["AdmissionSource"] = df["admission_source_id"].map(admission_source_map)

##### discharge group

In [29]:
def discharge_group(x):
    if x == 1:
        return "Home"

    elif x in [2,3,4,5]:
        return "Transferred"

    elif x in [6,7,8]:
        return "Home Health Care"

    elif x in [11,12,13,14,23,24]:
        return "Hospice"

    elif x in [18,25,26]:
        return "Psychiatric/Rehab"

    elif x in [22]:
        return "Expired"

    else:
        return "Other"

df["DischargeGroup"] = df["discharge_disposition_id"].apply(discharge_group)

##### Age sort

In [30]:
age_sort = {
    "[0-10)":1,
    "[10-20)":2,
    "[20-30)":3,
    "[30-40)":4,
    "[40-50)":5,
    "[50-60)":6,
    "[60-70)":7,
    "[70-80)":8,
    "[80-90)":9,
    "[90-100)":10
}

df["AgeSort"] = df["age"].map(age_sort)

##### Exporting

In [31]:
df.to_csv(
    "hospital_readmission_final.csv",
    index=False
)